platform :ios, '9.0'

target 'MyAsthmaApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyAsthmaApp

  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'KeychainSwift'
  pod 'SVProgressHUD'

  target 'MyAsthmaAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyAsthmaAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

